# Generated by Django 3.2.5 on 2022-04-03 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('frequency', models.DecimalField(decimal_places=3, max_digits=5)),
                ('nb_cores', models.IntegerField()),
                ('smt', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CpuBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('uid', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.category')),
            ],
            options={
                'unique_together': {('name', 'brand', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('loc_number', models.IntegerField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.site')),
            ],
            options={
                'unique_together': {('name', 'loc_number', 'site')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50, unique=True)),
                ('warranty_end', models.DateField(null=True)),
                ('ram', models.IntegerField()),
                ('addr_mac', models.CharField(max_length=12, unique=True)),
                ('storage', models.IntegerField()),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.cpu')),
            ],
            options={
                'unique_together': {('hostname', 'serial')},
            },
        ),
        migrations.CreateModel(
            name='Immo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_number', models.IntegerField(null=True)),
                ('buy_date', models.DateField(null=True)),
                ('inventory_number', models.IntegerField(unique=True)),
                ('cost_center', models.CharField(max_length=25, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.location')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('device_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.deviceuser')),
                ('immo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.immo')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='cpu',
            name='cpu_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.cpubrand'),
        ),
    ]
