# Generated by Django 3.2.5 on 2023-04-14 15:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('frequency', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('nb_cores', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CpuBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.category')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'unique_together': {('name', 'brand', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('loc_number', models.PositiveIntegerField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.entity')),
            ],
            options={
                'unique_together': {('name', 'loc_number', 'site')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=20)),
                ('serial', models.CharField(max_length=20, unique=True)),
                ('ram', models.PositiveSmallIntegerField(null=True)),
                ('addr_mac', models.CharField(max_length=17, null=True, unique=True)),
                ('storage', models.PositiveIntegerField(null=True)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.cpu')),
                ('operating_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.operatingsystem')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
            },
        ),
        migrations.CreateModel(
            name='Immo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_number', models.CharField(max_length=12, null=True)),
                ('inventory_number', models.IntegerField(unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.location')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=70, null=True, unique=True)),
                ('uid', models.CharField(max_length=10, unique=True)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.assignment')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.status')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=datetime.datetime(2023, 4, 14, 15, 24, 49, 85497, tzinfo=utc))),
                ('device_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.deviceuser')),
                ('immo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.immo')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
            options={
                'verbose_name': 'Périphérique',
                'verbose_name_plural': 'Périphériques',
            },
        ),
        migrations.AddField(
            model_name='cpu',
            name='cpu_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.cpubrand'),
        ),
    ]
