# Generated by Django 3.2.5 on 2023-04-14 15:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 15, 25, 14, 411807, tzinfo=utc)),
        ),
    ]
