# Generated by Django 3.2.5 on 2022-11-16 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20221102_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 9, 35, 26, 248261)),
        ),
    ]
