# Generated by Django 3.2.5 on 2022-11-16 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_device_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 9, 36, 18, 407143)),
        ),
    ]
