# Generated by Django 3.2.5 on 2022-11-19 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_device_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 17, 50, 13, 491644, tzinfo=utc)),
        ),
    ]
