# Generated by Django 3.2.5 on 2022-12-31 15:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_device_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 15, 25, 43, 114079, tzinfo=utc)),
        ),
    ]
