# Generated by Django 3.2.5 on 2023-01-06 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20230106_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 14, 11, 23, 78037, tzinfo=utc)),
        ),
    ]
