# Generated by Django 3.2.5 on 2023-02-11 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20230208_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 14, 42, 36, 70983, tzinfo=utc)),
        ),
    ]
